# YAML based on https://cloud.google.com/kubernetes-engine/docs/concepts/daemonset
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: mytimeds
spec:
  selector:
      matchLabels:
        name: mytimeds # Label selector that determines which Pods belong to the DaemonSet
  template:
    metadata:
      labels:
        name: mytimeds # Pod template's label selector
    spec:
      #nodeSelector:
      #  type: prod # Node label selector that determines on which nodes Pod should be scheduled
      #             # In this case, Pods are only scheduled to nodes bearing the label "type: prod"
      containers:
      - image: yoichikawasaki/mytime:1.0
        name: mytime
        stdin: true
        tty: true
        ports:
        - containerPort: 5000
        #resources:
        #  limits:
        #    memory: 200Mi
        #  requests:
        #    cpu: 100m
        #    memory: 200Mi
