apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: mytime
spec:
  template:
    metadata:
      labels:
        app: mytime
    spec:
      containers:
      - image: yoichikawasaki/mytime:1.0
        name: mytime
        stdin: true
        tty: true
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: mytime
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 5000
  selector:
    app: mytime
  type: ClusterIP
