version: '3'

services:
    gallery3:
        image: kuberdock/gallery3
        ports:
            - "8080:80"
        volumes:
            - /Users/yoichika/dev/docker/gallery3/gallery:/var/www/var/
            - /var/log
            - /Users/yoichika/dev/docker/gallery3/log:/var/log/apache2
        hostname: myhost
        domainname: localhost
